 #Simple Ubuntu-based Cloud Build configuration file
steps:
  # Step 1: Run commands on Ubuntu
  - name: 'ubuntu:20.04'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        echo "Starting build on Ubuntu..."
        apt-get update
        apt-get install -y curl git
        echo "Build complete successfully!"
        
  # Step 2: List files (optional verification step)
  - name: 'ubuntu:20.04'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        echo "Listing project files:"
        ls -la
options:
  logging: CLOUD_LOGGING_ONLY